export const restrictedActivities = [
  'a. Violates any law or government regulation, or promotes or facilitates such by third parties;',
  'b. Violates any rule or regulation of MasterCard International Inc., VISA U.S.A., Inc., DFS Services LLC d/b/a Discover Network (including any card issuer of payment cards processed and settled through the Discover network) and American Express Travel Related Services Company, Inc. ("American Express") or any other electronic funds transfer network (each, a “Payment Processor”);',
  'c. Is fraudulent, deceptive, unfair or predatory;',
  'd. Causes or threatens reputational damage to us or any Payment Processor;',
  'e. Involves any of the business categories listed in Section 2; or',
  'f. Results in or creates a significant risk of chargebacks, penalties, damages or other harm or liability.'
]

export const businessCategories = [
  'Age restricted products or services',
  'Aggregation or factoring, whether licensed or unlicensed',
  'Airlines (exceptions apply if you get our prior written approval)',
  'Bail bonds',
  'Bankruptcy lawyers',
  'Bidding fee auctions',
  'Business or investment opportunity sales',
  'Chain letters',
  'Check cashing, wire transfers or money orders',
  'Collection agencies',
  'Counterfeit goods or any product or service that infringes upon the copyright, trademark or trade secrets of any third party',
  'Credit card and identity theft protection',
  'Credit counseling, repair or protection services, or mortgage consulting or reduction services',
  'Cruise lines',
  'Currency exchanges or dealers',
  'Decryption and descrambler products designed to circumvent intellectual property rights or protections, including mod chips',
  'Door-to-door sales',
  'Drug paraphernalia',
  'Embassies, foreign consulates or other foreign governments',
  'Essay mills',
  'Evading card association chargeback monitoring programs',
  'Extended warranties',
  'Real estate purchases with no money down',
  'Flea markets',
  'Fortune tellers',
  'Gambling (including but not limited to lotteries, Internet gaming, contests, sweepstakes, or offering of prizes as an inducement to purchase goods or services) (exceptions apply in some countries/regions and if you get our prior written approval)',
  '“Get rich quick” schemes',
  'Human hair, fake hair or hair-extensions',
  'Loan modifiers',
  'Mail-order brides',
  'Marijuana dispensaries and related businesses',
  'Membership subscriptions > 1 year (exceptions apply if you get our prior written approval)',
  'Money transmitters or money service businesses',
  'Multi-level marketing or pyramid schemes',
  'Negative response marketing',
  'Offering substantial rebates or special incentives to the cardholder subsequent to the original purchase',
  'Online or other non-face-to-face pharmacies or pharmacy referral services',
  'Online or other non-face-to-face tobacco or e-cigarette sales',
  'Personal computer technical support (exceptions apply if you get our prior written approval)',
  'Prepaid phone cards, phone services or cell phones',
  'Pseudo pharmaceuticals',
  'Products/services that promote hate, violence, harassment or abuse, if illegal',
  'Quasi-cash or stored value',
  'Securities brokers',
  'Sexually-oriented or pornographic products or services',
  'Sharing cardholder’s data with another merchant for payment of up-sell or cross-sell products or services',
  'Shipping or forwarding brokers',
  'Social media activity sales (such as sales of Twitter followers, Facebook likes or YouTube views)',
  'Sports forecasting or odds making',
  'Prescription drugs, illegal drugs or substances designed to mimic illegal drugs',
  'Telecommunications equipment and telephone sales',
  'Telemarketing',
  'Timeshares',
  'Tour operators (exceptions apply if you get our prior written approval)',
  'Travel agencies or travel clubs (exceptions apply if you get our prior written approval)',
  'Virtual currency or credits that can be monetized, re-sold or converted to physical or digital goods or services or otherwise exit the virtual world',
  'Weapons and munitions',
  'Entertainment venues including but not limited to nightclubs, bars',
  'Pre-payment services'
]

export const actions = [
  'a. Blocking the settlement or completion of one or more payments;',
  'b. Suspending, restricting or terminating your access to and use of the Processing Services;',
  'c. Terminating our business relationship with you, including termination without liability to Luka of any payment service agreement between you and Luka;',
  'd. Taking legal action against you;',
  'e. Contacting and disclosing information related to such violations to (i) persons who have purchased goods or services from you, (ii) any banks or Payment Processor involved with your business or transactions, (iii) law enforcement or regulatory agencies, and (iv) other third parties that may have been impacted by such violations; or',
  'f. Assessing against you any fees, penalties, assessments or expenses (including reasonable attorneys’ fees) that we may incur as a result of such violations, which you agree to pay promptly upon notice.'
]
